### ISSUE TITLE
Sent message is still encrypted

### ISSUE THREAD

**Issue by stefanodvx** [opulentfox-29/protonmail-api-client#10]
When sending a message, it displays correctly on my ProtonMail app, but it's all encrypted on the recipient client. I'm 100% sure I'm using the right session and private key. 

This is my code:
```py3
    client = ProtonMail(logging_level=0)
    client.session.proxies = {
        "http": proxy,
        "https": proxy
    }
    client.load_session(f"sessions/{session_id}")
    client.pgp_import(
        private_key=io.StringIO(private_key),
        passphrase=password
    )
    object = object.replace("\n", "<br>")
    object = f"<html><body>{object}</body></html>"
    message = client.create_message(
        recipients=recipients,
        subject=subject,
        body=object
    )
    return client.send_message(message)
```

And this is how it displays on recipient client (Gmail, in this case):
![IMG_0065](https://github.com/opulentfox-29/protonmail-api-client/assets/69367859/ca43a5f0-e379-4dd9-a15a-b40eef78fc3f)

**Comment by stefanodvx** [comment]
Also, the preview message is always "hello" (cause of the payload used?). Another fact: this issue does not cover ANY message. Just a few. If you want to reproduce, please give me a private contact and I'll provide the body used.

**Comment by stefanodvx** [comment]
Update: if body exceeds 729 characters, it will cause this issue.

**Comment by opulentfox-29** [comment]
> I believe there's an issue with the MIMEText formatting for certain bodies.

You are right, the problem was that Base64 needs to be split into lines every 76 characters

>  the preview message is always "hello"

The message preview is always “hello”, because I didn’t know which one to put, there are 3 options:
1. allow the user to write a preview for the message himself
2. parsing text from HTML code
3. do not write preview for the message at all

Now I think that the “hello” preview is a bad idea, so I turned off the preview completely.
Your ideas/suggestions?
