### ISSUE TITLE
Avoid CAPTCHA

### ISSUE THREAD

**Issue by 12932** [opulentfox-29/protonmail-api-client#36]
I always get CAPTCHA not implemented. I understand that the request for a CAPTCHA comes from Protonmail, but how is everybody else avoiding a CAPTCHA? Even on my ISP home connection it prompts for CAPTCHA.. 

Any ideas?

**Comment by opulentfox-29** [comment]
The trigger mechanism of the captcha is unknown, I remember that I also always showed the captcha before, when I used some specific VPN (now I don’t remember which one).

The reasons for captcha are usually the following:
1. A massive DDOS attack is launched on the site, and therefore the site shows captcha to everyone (not our case)
2. Your IP is on their blacklist (the one who previously owned your IP could be an attacker)
3. Your provider/hosting is on their blacklist (one of the other users is an attacker)
4. They didn’t like your account for some reason (maybe you need to use the account for a long time and actively so that they have statistics)

I tried to get the captcha in different ways:
1. Created a new account from the TOR network
2. Logged into the account very often (only got a timeout for frequent logins)
3. Sent a lot of requests (5 parallel threads, nothing)
4. Sent mass emails that looked like spam (also nothing)
5. Changed IP using free popular VPNs (also nothing)

I never saw the captcha (except during the creation process account)

VPNs that I used:
1. Avira phantom vpn
2. Planet VPN
3. NordVPN
4. Windscribe

To bypass the captcha you can try:
1. Change your IP (just reboot the router, if you have a dynamic IP, it will change)
2. Register a new account (on a different IP and preferably on a non-suspicious browser, for example, Google Chrome without extensions)
3. Share mobile Internet
4. Use a VPN, for example, like the ones I gave as an example (try changing protocols in the VPN as well, I noticed that with the OpenVPN-UDP protocol some sites give a captcha)

If none of the above helped you, you can log in to your browser and copy the cookies from there:
1. Open the login page
2. Open the DevTools panel (f12)
3. Go to the "network" tab
4. Enable logging
5. Log in to the site (check "Keep me signed in")
6. Find the `api/core/v4/auth` request in the DevTools panel and open it
7. Copy the tokens from the response headers.
8. Paste into the code

```python
proton = ProtonMail()

proton.session.headers['x-pm-uid'] = 'lgfbju2dxc1234567890mrf3tqmqfhv6q'
proton.session.cookies['AUTH-lgfbju2dxc1234567890mrf3tqmqfhv6q'] = 'qr4uci1234567890anafsku8dd34vkwq'
proton.session.cookies['REFRESH-lgfbju2dxc1234567890mrf3tqmqfhv6q'] = '%7B%22ResponseType%22%3A%22token%22%2C%22ClientID%22%3A%22WebAccount%22%2C%22GrantType%22%3A%22refresh_token%22%2C%22RefreshToken%22%3A%22ceo5gp1234567890fghuinsxxtgmpvdduxg%22%2C%22UID%22%3A%22lgfbju2dxc1234567890mrf3tqmqfhv6q%22%7D'

proton._parse_info_after_login(password)
proton.save_session('session.pickle')
```

![image](https://github.com/user-attachments/assets/dd6f1193-3198-4751-8567-c9ca31c0ba8c)


P.S. if you log out of your account in the browser, the tokens will be invalidated, so log in to your account in an incognito tab, and then simply close the tab
